FROM python:3.12-slim

# Install uv.
COPY --from=ghcr.io/astral-sh/uv:0.6.10 /uv /uvx /bin/

# Copy the application into the container.
ADD . /app

# Install the application dependencies.
WORKDIR /app

# Install dependencies from requirements.txt
RUN uv pip install --system -r requirements.txt

EXPOSE 8000

# Run the application.
CMD ["uv", "run", "uvicorn", "gemini_backend.app:app", "--host", "0.0.0.0", "--port", "8000"]
